#include "../../random.h"
#include "../../block_stat.h"
#include "lib.h"
#include "mpi.h"
#include <string>
#include <iostream>
#include <iomanip>
#include <fstream>
#include <vector>
#include <math.h>
#include <cmath>
#include <complex>
#include <bits/stdc++.h>
